version: '3.3'

services:
  mongo_db:
    image: mongo:4.4
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27020:27017
    volumes:
      - ./mongo_data:/data/db
